// <auto-generated />
using System;
using MVCProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425085949_add data to accomodation and flights")]
    partial class adddatatoaccomodationandflights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCProject.Models.Accomodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableRooms")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Accomodations");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AvailableRooms = 10,
                            Image = "2.jpg",
                            Location = "New York",
                            Name = "The Ritz-Carlton",
                            PricePerNight = 150m
                        },
                        new
                        {
                            Id = 101,
                            AvailableRooms = 12,
                            Image = "2.jpg",
                            Location = "London",
                            Name = "Hilton Garden Inn",
                            PricePerNight = 175m
                        },
                        new
                        {
                            Id = 102,
                            AvailableRooms = 14,
                            Image = "2.jpg",
                            Location = "Paris",
                            Name = "Marriott Marquis",
                            PricePerNight = 200m
                        },
                        new
                        {
                            Id = 103,
                            AvailableRooms = 16,
                            Image = "2.jpg",
                            Location = "Tokyo",
                            Name = "Four Seasons Resort",
                            PricePerNight = 225m
                        },
                        new
                        {
                            Id = 104,
                            AvailableRooms = 18,
                            Image = "2.jpg",
                            Location = "Dubai",
                            Name = "InterContinental",
                            PricePerNight = 250m
                        },
                        new
                        {
                            Id = 105,
                            AvailableRooms = 20,
                            Image = "2.jpg",
                            Location = "Sydney",
                            Name = "Sheraton Grand",
                            PricePerNight = 275m
                        },
                        new
                        {
                            Id = 106,
                            AvailableRooms = 22,
                            Image = "2.jpg",
                            Location = "Rome",
                            Name = "Holiday Inn Express",
                            PricePerNight = 300m
                        },
                        new
                        {
                            Id = 107,
                            AvailableRooms = 24,
                            Image = "2.jpg",
                            Location = "Los Angeles",
                            Name = "Hyatt Regency",
                            PricePerNight = 325m
                        },
                        new
                        {
                            Id = 108,
                            AvailableRooms = 26,
                            Image = "2.jpg",
                            Location = "Barcelona",
                            Name = "Radisson Blu",
                            PricePerNight = 350m
                        },
                        new
                        {
                            Id = 109,
                            AvailableRooms = 28,
                            Image = "2.jpg",
                            Location = "Berlin",
                            Name = "Wyndham Grand",
                            PricePerNight = 375m
                        },
                        new
                        {
                            Id = 110,
                            AvailableRooms = 30,
                            Image = "2.jpg",
                            Location = "Singapore",
                            Name = "Fairmont",
                            PricePerNight = 400m
                        },
                        new
                        {
                            Id = 111,
                            AvailableRooms = 32,
                            Image = "2.jpg",
                            Location = "Hong Kong",
                            Name = "Mandalay Bay",
                            PricePerNight = 425m
                        },
                        new
                        {
                            Id = 112,
                            AvailableRooms = 34,
                            Image = "2.jpg",
                            Location = "Istanbul",
                            Name = "Bellagio",
                            PricePerNight = 450m
                        },
                        new
                        {
                            Id = 113,
                            AvailableRooms = 36,
                            Image = "2.jpg",
                            Location = "Bangkok",
                            Name = "The Venetian",
                            PricePerNight = 475m
                        },
                        new
                        {
                            Id = 114,
                            AvailableRooms = 38,
                            Image = "2.jpg",
                            Location = "Seoul",
                            Name = "Caesars Palace",
                            PricePerNight = 500m
                        },
                        new
                        {
                            Id = 115,
                            AvailableRooms = 40,
                            Image = "2.jpg",
                            Location = "Las Vegas",
                            Name = "MGM Grand",
                            PricePerNight = 525m
                        },
                        new
                        {
                            Id = 116,
                            AvailableRooms = 42,
                            Image = "2.jpg",
                            Location = "Miami",
                            Name = "Wynn Las Vegas",
                            PricePerNight = 550m
                        },
                        new
                        {
                            Id = 117,
                            AvailableRooms = 44,
                            Image = "2.jpg",
                            Location = "San Francisco",
                            Name = "Aria Resort",
                            PricePerNight = 575m
                        },
                        new
                        {
                            Id = 118,
                            AvailableRooms = 46,
                            Image = "2.jpg",
                            Location = "Chicago",
                            Name = "Cosmopolitan",
                            PricePerNight = 600m
                        },
                        new
                        {
                            Id = 119,
                            AvailableRooms = 48,
                            Image = "2.jpg",
                            Location = "Toronto",
                            Name = "The Mirage",
                            PricePerNight = 625m
                        });
                });

            modelBuilder.Entity("MVCProject.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MVCProject.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MVCProject.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MVCProject.Models.BookingAccomodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccomodationId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationId");

                    b.HasIndex("BookingId", "AccomodationId")
                        .IsUnique();

                    b.ToTable("BookingAccomodations");
                });

            modelBuilder.Entity("MVCProject.Models.BookingActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("BookingId", "ActivityId")
                        .IsUnique();

                    b.ToTable("BookingActivities");
                });

            modelBuilder.Entity("MVCProject.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Airline = "Emirates",
                            ArrivalDateTime = new DateTime(2025, 1, 2, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 100,
                            DepartureAirport = "JFK",
                            DepartureDateTime = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "SYD",
                            Price = 300m
                        },
                        new
                        {
                            Id = 101,
                            Airline = "Delta Air Lines",
                            ArrivalDateTime = new DateTime(2025, 1, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 105,
                            DepartureAirport = "LHR",
                            DepartureDateTime = new DateTime(2025, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "FCO",
                            Price = 315m
                        },
                        new
                        {
                            Id = 102,
                            Airline = "Qatar Airways",
                            ArrivalDateTime = new DateTime(2025, 1, 4, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 110,
                            DepartureAirport = "CDG",
                            DepartureDateTime = new DateTime(2025, 1, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "LAX",
                            Price = 330m
                        },
                        new
                        {
                            Id = 103,
                            Airline = "Singapore Airlines",
                            ArrivalDateTime = new DateTime(2025, 1, 5, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 115,
                            DepartureAirport = "HND",
                            DepartureDateTime = new DateTime(2025, 1, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "BCN",
                            Price = 345m
                        },
                        new
                        {
                            Id = 104,
                            Airline = "United Airlines",
                            ArrivalDateTime = new DateTime(2025, 1, 6, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 120,
                            DepartureAirport = "DXB",
                            DepartureDateTime = new DateTime(2025, 1, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "BER",
                            Price = 360m
                        },
                        new
                        {
                            Id = 105,
                            Airline = "Lufthansa",
                            ArrivalDateTime = new DateTime(2025, 1, 7, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 125,
                            DepartureAirport = "SYD",
                            DepartureDateTime = new DateTime(2025, 1, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "SIN",
                            Price = 375m
                        },
                        new
                        {
                            Id = 106,
                            Airline = "British Airways",
                            ArrivalDateTime = new DateTime(2025, 1, 8, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 130,
                            DepartureAirport = "FCO",
                            DepartureDateTime = new DateTime(2025, 1, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "HKG",
                            Price = 390m
                        },
                        new
                        {
                            Id = 107,
                            Airline = "Air France",
                            ArrivalDateTime = new DateTime(2025, 1, 9, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 135,
                            DepartureAirport = "LAX",
                            DepartureDateTime = new DateTime(2025, 1, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "IST",
                            Price = 405m
                        },
                        new
                        {
                            Id = 108,
                            Airline = "Cathay Pacific",
                            ArrivalDateTime = new DateTime(2025, 1, 10, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 140,
                            DepartureAirport = "BCN",
                            DepartureDateTime = new DateTime(2025, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "BKK",
                            Price = 420m
                        },
                        new
                        {
                            Id = 109,
                            Airline = "Qantas",
                            ArrivalDateTime = new DateTime(2025, 1, 11, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 145,
                            DepartureAirport = "BER",
                            DepartureDateTime = new DateTime(2025, 1, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "ICN",
                            Price = 435m
                        },
                        new
                        {
                            Id = 110,
                            Airline = "American Airlines",
                            ArrivalDateTime = new DateTime(2025, 1, 12, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 150,
                            DepartureAirport = "SIN",
                            DepartureDateTime = new DateTime(2025, 1, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "LAS",
                            Price = 450m
                        },
                        new
                        {
                            Id = 111,
                            Airline = "ANA",
                            ArrivalDateTime = new DateTime(2025, 1, 13, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 155,
                            DepartureAirport = "HKG",
                            DepartureDateTime = new DateTime(2025, 1, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "MIA",
                            Price = 465m
                        },
                        new
                        {
                            Id = 112,
                            Airline = "Etihad Airways",
                            ArrivalDateTime = new DateTime(2025, 1, 14, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 160,
                            DepartureAirport = "IST",
                            DepartureDateTime = new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "SFO",
                            Price = 480m
                        },
                        new
                        {
                            Id = 113,
                            Airline = "Turkish Airlines",
                            ArrivalDateTime = new DateTime(2025, 1, 15, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 165,
                            DepartureAirport = "BKK",
                            DepartureDateTime = new DateTime(2025, 1, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "ORD",
                            Price = 495m
                        },
                        new
                        {
                            Id = 114,
                            Airline = "Air Canada",
                            ArrivalDateTime = new DateTime(2025, 1, 16, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 170,
                            DepartureAirport = "ICN",
                            DepartureDateTime = new DateTime(2025, 1, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "YYZ",
                            Price = 510m
                        },
                        new
                        {
                            Id = 115,
                            Airline = "KLM",
                            ArrivalDateTime = new DateTime(2025, 1, 17, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 175,
                            DepartureAirport = "LAS",
                            DepartureDateTime = new DateTime(2025, 1, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "JFK",
                            Price = 525m
                        },
                        new
                        {
                            Id = 116,
                            Airline = "Japan Airlines",
                            ArrivalDateTime = new DateTime(2025, 1, 18, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 180,
                            DepartureAirport = "MIA",
                            DepartureDateTime = new DateTime(2025, 1, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "LHR",
                            Price = 540m
                        },
                        new
                        {
                            Id = 117,
                            Airline = "Swiss Airlines",
                            ArrivalDateTime = new DateTime(2025, 1, 19, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 185,
                            DepartureAirport = "SFO",
                            DepartureDateTime = new DateTime(2025, 1, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "CDG",
                            Price = 555m
                        },
                        new
                        {
                            Id = 118,
                            Airline = "Virgin Atlantic",
                            ArrivalDateTime = new DateTime(2025, 1, 20, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 190,
                            DepartureAirport = "ORD",
                            DepartureDateTime = new DateTime(2025, 1, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "HND",
                            Price = 570m
                        },
                        new
                        {
                            Id = 119,
                            Airline = "Air New Zealand",
                            ArrivalDateTime = new DateTime(2025, 1, 21, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 195,
                            DepartureAirport = "YYZ",
                            DepartureDateTime = new DateTime(2025, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirport = "DXB",
                            Price = 585m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVCProject.Models.Booking", b =>
                {
                    b.HasOne("MVCProject.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCProject.Models.AppUser", "AppUser")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("MVCProject.Models.BookingAccomodation", b =>
                {
                    b.HasOne("MVCProject.Models.Accomodation", "Accomodation")
                        .WithMany("bookingAccomodations")
                        .HasForeignKey("AccomodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCProject.Models.Booking", "Booking")
                        .WithMany("bookingAccomodations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accomodation");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MVCProject.Models.BookingActivity", b =>
                {
                    b.HasOne("MVCProject.Models.Activity", "Activity")
                        .WithMany("BookingActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCProject.Models.Booking", "Booking")
                        .WithMany("BookingActivities")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MVCProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MVCProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MVCProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVCProject.Models.Accomodation", b =>
                {
                    b.Navigation("bookingAccomodations");
                });

            modelBuilder.Entity("MVCProject.Models.Activity", b =>
                {
                    b.Navigation("BookingActivities");
                });

            modelBuilder.Entity("MVCProject.Models.AppUser", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MVCProject.Models.Booking", b =>
                {
                    b.Navigation("BookingActivities");

                    b.Navigation("bookingAccomodations");
                });

            modelBuilder.Entity("MVCProject.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
